 export const productData = [
    {
      id: "5676849392",
      title: "TECKNET Wireless Mouse, 2.4G USB Computer Mouse with 6-Level Adjustable 4800 DPI, 30 Months Battery, Ergonomic Grips, 6 Buttons Portable for PC, Chromebook, Mac - Grey",
      isNew: true,
      inStock: true,
      oldPrice: "15",
      price: 9,
      description:"TECKNET wireless mouse has a 6-Level adjustable DPI (800/1200/1600/2400/3200/4800), which provides more sensitivity than standard optical mice for smooth and precise tracking on a wide range of surfaces.Designed with the upgraded independent power switches and sleep modes to minimize battery consumption, the wireless mouse can enjoy up to 30 months of use time with only 2 AA batteries (not included). 2X longer battery life than others.The wireless mouse has a 50ft/15m wireless use range, which reduces interference and delay for you. No need to install any drivers, plug the TECKNET wireless mouse into the device and you are ready to go!",
      category: "Mouse",
      brand: "tecknet",
      image:
        "https://m.media-amazon.com/images/I/61agI90cKJL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
      rating: 4,
      quantity: 1,
    },
    {
      id: "25474378893",
      title: "Logitech M185 Wireless Mouse, 2.4GHz with USB Mini Receiver, 12-Month Battery Life, 1000 DPI Optical Tracking, Ambidextrous PC/Mac/Laptop - Swift Gray",
      isNew: true,
      inStock: true,
      oldPrice: "18",
      price: 15,
      description:" With a comfortable and contoured shape, this Logitech ambidextrous wireless mouse feels great in either right or left hand and is far superior to a touchpad This USB wireless mouse features a line-by-line scroll wheel; up to 1 year of battery life (2) thanks to a smart sleep mode function, and comes with the included AA battery Your Logitech mouse works with your Windows PC, Mac, or laptop, so no matter what type of computer you own today or buy tomorrow your mouse will be compatible Just plug in the tiny nano USB receiver and start working in seconds with a strong, reliable connection to your wireless computer mouse up to 33 feet / 10 m (5) Get more done by adding M185 to your laptop; according to a recent study, laptop users who chose this mouse over a touchpad were 50% more productive (3) and worked 30% faster (4)",
        category: "Mouse",
        brand: "logitech",
      image:
        "https://m.media-amazon.com/images/I/61N+CzcA8vL._AC_SY300_SX300_.jpg",
      rating: 3,
      quantity: 1,
    },
    {
      id: "3638901297783",
      title: "Manhattan Wired Computer Keyboard – Basic Black Keyboard - with 4.5ft USB-A Cable, 104-keys, Foldable Stands - Compatible for Windows, PC, Laptop - 3 Yr Mfg Warranty – 179324",
      isNew: true,
      inStock: true,
      oldPrice: "20",
      price: 18.99,
      description:"Full-sized Keyboard: Offers 104 keys, including navigational controls, full functions and a 10-key keypad Easily connects you to your PC or laptop right away so you can get working or playing Keyboard's 4.5ft. wired connection gives you plenty of room to setup your keyboard where you want it Includes key status indicators for Num Lock, Caps Lock, Scroll Lock functions",
      category: "Keyboard",
      brand: "manhattan",
      image:
        "https://m.media-amazon.com/images/I/61s6ZL3Vg3L.__AC_SX300_SY300_QL70_FMwebp_.jpg",
      rating: 3,
      quantity: 1,
    },
    {
      id: "474889930023",
      title: "22 Inch Monitor with HDMI VGA Port, 1080P 75Hz Full HD VA LED Ultra Thin Bezel Display, Flicker-Free, Blue Light Filter, Built-in Speakers, Tilt Adjustment",
      isNew: true,
      inStock: true,
      oldPrice: "96",
      price: 65.96,
      description:" 21.5-inch monitor, resolution: 1920*1080P, 75HZ, color gamut 99% sRGB (NTSC 72%), response time 6ms, dynamic contrast ratio 20 million.This moniter uses VA LED Display, horizontal and vertical viewing angle 178 degrees, and unique anti-blue light filtering function. Protect your eyes while providing you with better picture quality. We care about the health of the user's neck. Norcent computer moniters has an adjustable tilt angle from 5° to -15°. Norcent monitor has HDMI, VGA, 3.5mm audio output ports, easy to link various devices. Let this monitor be your partner when you are gaming/assistant when you are working/companion when you are relaxing. The Norcent team is committed to providing customers with quality products and services. If you have any problems after purchasing our products, you can contact us at any time and we will help you solve your problems at the first time.",
      category: "Monitor",
      brand: "monitor",
      image:
        "https://m.media-amazon.com/images/I/61yezqnxooL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
      rating: 3,
      quantity: 1,
    },
    {
      id:"564834903092" ,
      title: "HP 14 Laptop Ultral Light for Students and Business, Quad-Core Intel Celeron Processor, 8GB RAM, 256GB Storage (128GB eMMC + 128GB Ghost Manta SD Card), HDMI, WiFi, USB-A&C, Win 11 ",
      isNew: true,
      inStock: true,
      oldPrice: "500",
      price: 357,
      description:"14.0-inch diagonal, HD (1366 x 768), micro-edge, BrightView. With virtually no bezel encircling the display, an ultra-wide viewing experience provides for seamless multi-monitor set-ups Intel Celeron N4120, 4 Cores & 4 Threads, 1.10 GHz Base Frequency, Up to 2.60 GHz Burst Frequency, 4 MB Cahce, Intel UHD Graphics 600, Handle multitasking reliably with the perfect combination of performance, power consumption, and value. Upgraded to 8GB high-bandwidth DDR4 Memory (2400 MHz), Adequate high-bandwidth RAM to smoothly run multiple applications and browser tabs all at once. 128GB high-speed eMMC Storage for your office and webinar needs. With 128GB Ghost Manta SD Card.",
      category: "Laptop",
      brand: "hp",
      image:
        "https://m.media-amazon.com/images/I/61cW3oKmQBL.__AC_SY300_SX300_QL70_FMwebp_.jpg",
      rating: 5,
      quantity: 1,
    },
    {
      id: "67684993092",
      title: "HP 14 Laptop Ultral Light for Students and Business, Quad-Core Intel Celeron Processor,",
      isNew: false,
      inStock: false,
      oldPrice: "350",
      price: 259,
      description:"14.0-inch diagonal, HD (1366 x 768), micro-edge, BrightView. With virtually no bezel encircling the display, an ultra-wide viewing experience provides for seamless multi-monitor set-ups Intel Celeron N4120, 4 Cores & 4 Threads, 1.10 GHz Base Frequency, Up to 2.60 GHz Burst Frequency, 4 MB Cahce, Intel UHD Graphics 600, Handle multitasking reliably with the perfect combination of performance, power consumption, and value. Upgraded to 16GB high-bandwidth DDR4 Memory (2400 MHz), Adequate high-bandwidth RAM to smoothly run multiple applications and browser tabs all at once. 128GB high-speed eMMC Storage for your office and webinar needs. With 64GB Ghost Manta SD Card.",
     category: "Laptop",
     brand: "hp",
      image:
        "https://m.media-amazon.com/images/I/61IKSn0q9bL.__AC_SY300_SX300_QL70_FMwebp_.jpg",
      rating: 4,
      quantity: 1,
    },
    {
      id: "76478899923",
      title: "Apple iPhone 13, 128GB, Blue",
      isNew: false,
      inStock: true,
      oldPrice: "600",
      price: 489,
      description:"6.1 Super Retina XDR display. 5G Superfast downloads, high?quality streaming Cinematic mode in 1080p at 30 fps. Dolby Vision HDR video recording up to 4K at 60 fps. 2X Optical zoom range A15 Bionic chip. New 6-core CPU with 2 performance and 4 efficiency cores. New 4-core GPU. New 16-core Neural Engine  Up to 19 hours video playback. Face ID. Ceramic Shield front. Aerospace-grade aluminum",
       category: "Phone",
       brand: "apple",
      image:
        "https://m.media-amazon.com/images/I/51ysOQMyoGL._AC_SX679_.jpg",
      rating: 2,
      quantity: 1,
    },
    {
      id: "853789209834",
      title: "Samsung Galaxy S21 FE 5G, Factory Unlocked, 128GB, 120Hz Display Screen, Pro Grade Camera, US Version, White - (Renewed)",
      isNew: false,
      inStock:true,
      oldPrice: "300",
      price: 205,
      description:"6.4 FHD+ Dynamic AMOLED 2X, Infinity-O Display (2400x1080), 401ppi, HDR10+ certified, 120Hz refresh rate 128GB ROM, 6GB RAM, Qualcomm SM8350 Snapdragon 888 5G (5 nm), Octa-core, 4500mAh Battery Rear Camera: 12MP Ultra-Wide + 12MP Wide-angle + 8MP Telephoto, Front Camera: 32MP, Under Display Fingerprint 2G: GSM 850/900/1800/1900, CDMA 800/1900 / TD-SCDMA, 3G: HSDPA 850/900/1700(AWS)/1900/2100, CDMA2000 1xEV-DO, 4G: LTE 1/2/3/4/5/7/12/13/29/25/26/28/38/39/40/41/46/48/66/71, 5G: 41/66/71/260/261 SA/NSA/Sub6 (ensure to check compatibility with your carrier before purchase) US Model. Fully Unlocked Version. Compatible with Most GSM and CDMA Carriers like AT&T, T-Mobile, AT&T, MetroPCS, etc. Will Also work with CDMA Carriers Such as Verizon, Sprint.",
        category: "Phone",
        brand: "samsung",
      image:
        "https://m.media-amazon.com/images/I/61PPEjwAkYL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
      rating: 3,
      quantity: 1,
    },
    {
      id: "9764788930",
      title: "SAMSUNG Galaxy S24 Ultra Cell Phone, 512GB AI Smartphone, Unlocked Android, 50MP Zoom Camera, Long Battery Life, S Pen, US Version, 2024, Titanium Yellow",
      isNew: false,
      inStock: false,
      oldPrice: "2000",
      price: 1219,
      description:"CIRCLE & SEARCH¹ IN A SNAP: What’s your favorite influencer wearing? Where’d they go on vacation? What’s that word mean? Don’t try to describe it — use Circle to Search1 with Google to get the answer; With S24 Series, circle it on your screen and learn more REAL EASY, REAL-TIME TRANSLATIONS: Speak foreign languages on the spot with Live Translate²; Unlock the power of convenient communication with near real-time voice translations, right through your Samsung Phone app NOTE SMARTER, NOT HARDER: Focus on capturing your notes and spend less time perfecting them; Note Assist³ will summarize, format, and even translate them for you; All of your notes are organized neatly so that you can find what you need BRING DETAILS OUT OF THE DARKNESS: Brighten up your night with Nightography on S24 Ultra; Want a closer look? Zoom in from a distance, even in low light MORE WOW, LESS WORK: Turn every photo into a post-worthy masterpiece; Move or remove objects; Fill in empty space; Simply snap a pic and take it from great to jaw-dropping with Generative Edit⁴ CAPTURE. SHARE. IMPRESS: Create crystal-clear content worth sharing; From bustling cityscape to a serene landscape, capture a masterpiece of detail with 200MP camera and let S24 Ultra adjust each hue and shade to reflect the world as you see it OUR MOST POWERFUL GALAXY SMARTPHONE YET: Jump seamlessly between apps without the wait and see content in high quality with our fastest processor yet, Snapdragon 8 Gen 3 for Galaxy⁵",
        category: "Phone",
        brand: "samsung",
        specification: [
          {Oprating_System: "Android 14, One UI 6.1"},
          {Ram_Memory: "12 GB"},
           { Memory_storage :"512 GB"}
        ],
      image:
        "https://m.media-amazon.com/images/I/71ZoDT7a2wL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
      rating: 3,
      quantity: 1,
    },
    {
      id: "1064783788",
      title: "Apple 2024 MacBook Air 13-inch Laptop with M3 chip: 13.6-inch Liquid Retina Display, 8GB Unified Memory, 256GB SSD Storage, Backlit Keyboard, 1080p FaceTime HD Camera, Touch ID; Space Gray",
      isNew: false,
      inStock: true,
      oldPrice: "1000",
      price: 989.01,
      description:"LEAN. MEAN. M3 MACHINE — The blazing-fast MacBook Air with the M3 chip is a superportable laptop that sails through work and play. PORTABLE DESIGN — Lightweight and under half an inch thin, so you can take MacBook Air anywhere you go. GET MORE DONE FASTER — The powerful 8-core CPU and up to 10-core GPU of the Apple M3 chip keep things running smoothly. UP TO 18 HOURS OF BATTERY LIFE — Amazing, all-day battery life so you can leave the power adapter at home. A BRILLIANT DISPLAY — The 13.6-inch Liquid Retina display supports 1 billion colors. LOOK SHARP, SOUND GREAT — Everything looks and sounds amazing with a 1080p FaceTime HD camera, three mics, and four speakers with Spatial Audio. APPS FLY WITH APPLE SILICON — All your favorites, from Microsoft 365 to Adobe Creative Cloud, run lightning fast in macOS.",
          category: "Laptop",
          brand: "apple",
      image:
        "https://m.media-amazon.com/images/I/71ItMeqpN3L.__AC_SY445_SX342_QL70_FMwebp_.jpg",
      rating: 5,
      quantity: 1,
    },
    {
      id: "114567899093",
      title: "2017 Apple Macbook Air with 1.8GHz Intel Core i5 (13-inch, 8GB RAM, 128GB SSD Storage) (QWERTY English) Silver",
      isNew: false,
      inStock: false,
      oldPrice: "300",
      price: 226,
      description:"Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter for use in your destination. Please check compatibility before purchasing.",
         category: "Laptop",
      brand:"apple",
      image:
        "https://m.media-amazon.com/images/I/61U4MibK9tL._AC_SX679_.jpg",
      rating: 4,
      quantity: 1,
    },
    {
      id: "12546783993",
      title: "ZIHNIC Bluetooth Headphones Over-Ear, Foldable Wireless and Wired Stereo Headset Micro SD/TF, FM for Cell Phone,PC,Soft Earmuffs &Light Weight for Prolonged Wearing(Rose Gold)",
      isNew: false,
      inStock: true,
      oldPrice: "36",
      price: 21,
      description:"【ASTONISHING SOUND PRODUCTION 】: High Definition Stereo Headphones, specially developed software and noise reduction technology designed to prevent you from heating ambient noises and makes you focus on what you want to hear. Lose yourself in immersive music even in the lowest volume levels! The goal that provide Customers with outstanding sound quality is our constant pursuit【BUILT FOR YOUR COMFORTABILITY 】: The Earmuff is made by artificial leather, ensuring lasting comfort. They are foldable and stretchable, which allows you to find the perfect fit without constraint and excellent durability. Zihnic is the best choice for travel, sport and daily use by Unisex Kids, Teens and Adults.【SEAMLESS BLUETOOTH CONNECTION】: Built to provide a quick and stable Bluetooth connection . Just slide the on/off button and the headphones will be in ready to pair mode. The Wireless Headphones are compatible with all Bluetooth or 3.5mm plug cable enabled devices! You can also receive calls and have hands-free communication through the special noise reduction technology microphone Zihnic Headphones are compatible with all Phones X, 8 Plus, Samsung S9, S8, Pads, Pods, Huawei, Nexus, Amazon Alex",
       category: "Headphone",
      brand: "zihnic",
      image:
        "https://m.media-amazon.com/images/I/51eAhFCg5mL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
      rating: 3,
      quantity: 1,
    },
    {
      id: "1367489930903",
      title: "AILIHEN C8 Headphones Wired, On-Ear Headphones with Microphone and Volume Control Foldable Corded Stereo 3.5mm Headset for Smartphones Chromebook Laptop Computer PC Tablets Travel(Black/Blue)",
      isNew: false,
      inStock: true,
      oldPrice: "46",
      price: 19,
      description:"Collapsible Feature: Take your wired headphones wherever you go. Just fold them up, twist up the cord, and be on your merry way Hands-free Talking and Volume Control: The built-in mic,remote and volume control lets you pick up calls and skip between tracks without missing a beat. Adjustable Hinge: The adjustable headband gives your headphones some impressive flexibility so they can adapt to the shape of your head for a perfect fit. Noise Isolation: full-sized, on-ear construction isolates from outside noise so you can hear the deep bass, and crisp mids and highs of your upcoming track. Widely Compatible: with a flexible and durable 47 inches braided cord and sturdy 3. 5 mm stereo Plug. Will not kink, twist or break under normal use. Use with all your favorite devices like cellphones, laptop, computer, Chromebook, MP3, MP4 and other Audio devices",
       category: "Headphone",
      brand: "ailihen",
      image:
        "https://m.media-amazon.com/images/I/81AMLwVWSfL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
      rating: 4,
      quantity: 1,
    },
    {
      id: "145658930478",
      title: "BestOffice High-Back Gaming Chair PC Office Chair Computer Racing Chair PU Desk Task Chair Ergonomic Executive Swivel Rolling Chair with Lumbar Support for Back Pain Women, Men,White",
      isNew: true,
      inStock: true,
      oldPrice: "100",
      price: 89,
      description:"Pu Leather COMFORT FROM EVERY ANGLE - Our high-back gaming chair is thickly cushioned for maximum comfort, whether you’re spending long hours at the office, in front of the computer, or gaming. Covered with breathable premium PU leather, the chair is equipped with freely adjustable lumbar support and a headrest pillow to protect your spine and neck, while the adjustable reclining feature allows users to lock in any reclining position, from 90-135°. MAXIMUM MOBILITY - Our chair are designed with long-lasting ergonomic construction, equipped with a BIFMA-certified heavy-duty metal base, providing stability and mobility with a 360° range of motion on smooth-rolling nylon casters so you can glide easily between work stations. EASY ASSEMBLY – Our chair comes ready to assemble, with all the hardware and necessary tools. With step-by-step instructions, you’ll be set up and ready to game, take on the office in about 10-15 minutes! CUSTOMER GUARANTEE – We want all of our customers to feel 100% satisfied, and ready to unwind from the comfort of our High-Back Office Chair. If you’re not satisfied, or have any questions, please contact BestOffice customer service. BUILT TO LAST - The high-back chair is built to endure, with a heavy-duty metal base, offering great stability and mobility for a capacity of up to 250 lbs.",
        category: "chair",
      brand: "ergonomic chair",
      image:
        "https://m.media-amazon.com/images/I/61t4mpabO+L._AC_SY300_SX300_.jpg",
      rating: 2,
      quantity: 1,
    },
    {
      id: "156784990956",
      title: " GTRACING Gaming Chair with Footrest Speakers Video Game Chair Bluetooth Music Heavy Duty Ergonomic Computer Office Desk Chair Red",
      isNew: true,
      inStock: true,
      oldPrice: "200",
      price: 150,
      description:"Designed with 2 Bluetooth speakers.Surrounded sound system brings the best in your entertainment Connect it to your smartphone, tablet or other Bluetooth enabled devices,and enjoy music,mobile gameErgonomic Design: Strong metal frame designed to help promote a comfortable seated position Multi Function: Bluetooth speakers for 16 hour music play,Armrest adjustable,Seat height adjustable Seat height adjustable;90 to 160 degree reclining;360 degree swivel;Removable headrest High Quality: Smooth Pu leather upholstery.Thick padded seat cushion made of high density foam  Game and Office: Gtracing gaming chair is an ideal seat of choice for working, studying and gaming",
         category: "chair",
      brand: "gtracing",
      image:
        "https://m.media-amazon.com/images/I/71y9SgG-XaS.__AC_SX300_SY300_QL70_FMwebp_.jpg",
      rating: 4,
      quantity: 1,
    },
    {
      id: "1656748909256",
      title: "Redragon S101 Gaming Keyboard, M601 Mouse, RGB Backlit Gaming Keyboard, Programmable Backlit Gaming Mouse, Value Combo Set",
      isNew: true,
      inStock: true,
      oldPrice: "60",
      price: 35,
      description:"PC GAMING KEYBOARD AND GAMING MOUSE COMBO: Includes Redragon RGB Backlit Computer Gaming Keyboard and RGB Backlit Gaming Mouse. ALL-IN-ONE PC GAMER VALUE KIT, Fantastic for Gamers (New Improved Version) RGB BACKLIT GAMING KEYBOARD; 7 different RGB Lighting modes & effects, 4 backlight brightness levels, adjustable breathing speed. The keycaps offering clear uniform backlighting WIN key can be disabled for gaming. The PC Gaming Keyboard has been ergonomically designed to be a superb typing tool for office work as well. The gaming Keyboard is built to withstand the average liquid spill. The integrated wrist rest gives you the comfort you need for marathon gaming sessions MULTI MEDIA & ANTI GHOSTING; The Gaming Keyboard has 25 conflict free (n-Key Rollover) 10 Dedicated Multimedia keys plus 12 additional FN+ Multimedia keys (Total 114 keys). Keys are quiet, designed for longevity, durability delivering precise tactile feedback. Comes with Full numeric keypad and a gold-plated corrosion free USB connector for a reliable connection and ultimate Gaming performance",
       category: "Keyboard",
      brand: "redragon",
      image:
        "https://m.media-amazon.com/images/I/71QDJHG1PqL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
      rating: 4,
      quantity: 1,
    },
    {
      id: "176467889263",
      title: "SAMSUNG Galaxy Tab A9+ Tablet 11” 128GB Android Tablet, Big Screen, Quad Speakers, Upgraded Chipset, Multi Window Display, Slim, Light, Durable Design, US Version, 2024, Graphite",
      isNew: true,
      inStock: true,
      oldPrice: "350",
      price: 229,
      description:"BIG SCREEN. FAMILY-SIZED FUN: Bring fun home to everyone with a bright, engaging 11 screen¹ ; A refresh rate of up to 90Hz makes every experience feel smooth — great for videos, games or fun time for the kids RICH SOUND ALL AROUND: Your music; Your shows; Your games; Hear them all loud and clear, thanks to quad speakers powered by Dolby Atmos; Galaxy Tab A9+ delivers a cinema-like audio experience your ears will love POWER FOR ALL YOU DO. STORAGE FOR ALL YOU LOVE: Watch videos, play games and do more with an upgraded chipset; Keep everything you love together with up to 128GB² of storage and microSD support³ SEE & USE MULTIPLE APPS AT ONCE: Open multiple apps⁴ at once with Galaxy Tab A9+ and accomplish more seamlessly; Bounce between the things like a multitasking pro — browse the internet, check email and jot down notes all on one screen LOVED BY KIDS. TRUSTED BY PARENTS: Give your kids a safe place to learn and play with the Samsung Kids app⁵ ; Kids will love a wide variety of playful, colorful content that keeps them entertained while stimulating their young minds  SLIM. LIGHT. DURABLE: Carry your Tab easily with a slim, light design that’s also durable; Galaxy Tab A9+ is the perfect blend of performance and portability to help you bring the fun with you wherever you go",
        category: "Tablet",
      brand: "samsung",
      image:
        "https://m.media-amazon.com/images/I/61d46oYQgdL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
      rating: 3,
      quantity: 1,
    },
    {
      id: "18568930026",
      title: "Fitness Tracker Watch with Heart Rate Monitor, Activity Tracker with Pedometer, Sleep Monitor, Calories & Step Counter, 5ATM Waterproof Smart Watch for Women Men Health Fitness Watch for Sports",
      isNew: true,
      inStock: true,
      oldPrice: "30",
      price: 19,
      description:" Heart Rate and Sleep Monitoring: The Fitness Tracker monitors your heart rate automatically all day, and you can select manual mode through the App. The fitness Watch also monitors your sleep at night, providing a detailed analysis of your sleep quality (deep sleep, light sleep, awake time). It is a health advisor for women men in daily life. Multi Sport Modes with Activity Tracking: The fitness tracker features 9 sport modes like running, walking and more. Additionally, the activity tracker records daily steps, calories burned, walking distance and active time throughout the day. You can also set a daily steps goals through the App to track your progress.Smart Notification Reminder: You can get SMS messages, and SNS notifications directly on your wrist including Facebook, Twitter, Gmail ect. You won't miss any important calls and message and stay updated. Please note: the smart watch can not make calls or text. Long Battery Life and IP68 Waterproof: This smart watch only requires 2 hours of charging and can be used for 5-7 days continuously. 5ATM waterproof rating can withstand daily sweat, washing hands and rainy day, allowing you to fully enjoy your workouts.",
        category: "watch",
      brand: "apple",
      image:
        "https://m.media-amazon.com/images/I/71sATQpfivL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
      rating: 4,
      quantity: 1,
    },

  ];
 export const newarrival = [
  {
    id: "853789209834",
    title: "Samsung Galaxy S21 FE 5G, Factory Unlocked, 128GB, 120Hz Display Screen, Pro Grade Camera, US Version, White - (Renewed)",
    isNew: true,
    inStock:true,
    oldPrice: "300",
    price: 205,
    description:"6.4 FHD+ Dynamic AMOLED 2X, Infinity-O Display (2400x1080), 401ppi, HDR10+ certified, 120Hz refresh rate 128GB ROM, 6GB RAM, Qualcomm SM8350 Snapdragon 888 5G (5 nm), Octa-core, 4500mAh Battery Rear Camera: 12MP Ultra-Wide + 12MP Wide-angle + 8MP Telephoto, Front Camera: 32MP, Under Display Fingerprint 2G: GSM 850/900/1800/1900, CDMA 800/1900 / TD-SCDMA, 3G: HSDPA 850/900/1700(AWS)/1900/2100, CDMA2000 1xEV-DO, 4G: LTE 1/2/3/4/5/7/12/13/29/25/26/28/38/39/40/41/46/48/66/71, 5G: 41/66/71/260/261 SA/NSA/Sub6 (ensure to check compatibility with your carrier before purchase) US Model. Fully Unlocked Version. Compatible with Most GSM and CDMA Carriers like AT&T, T-Mobile, AT&T, MetroPCS, etc. Will Also work with CDMA Carriers Such as Verizon, Sprint.",
      category: "Phone",
      brand: "samsung",
    image:
      "https://m.media-amazon.com/images/I/61PPEjwAkYL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    rating: 3,
    quantity: 1,
  },
  {
    id: "9764788930",
    title: "SAMSUNG Galaxy S24 Ultra Cell Phone, 512GB AI Smartphone, Unlocked Android, 50MP Zoom Camera, Long Battery Life, S Pen, US Version, 2024, Titanium Yellow",
    isNew: true,
    inStock: false,
    oldPrice: "2000",
    price: 1219,
    description:"CIRCLE & SEARCH¹ IN A SNAP: What’s your favorite influencer wearing? Where’d they go on vacation? What’s that word mean? Don’t try to describe it — use Circle to Search1 with Google to get the answer; With S24 Series, circle it on your screen and learn more REAL EASY, REAL-TIME TRANSLATIONS: Speak foreign languages on the spot with Live Translate²; Unlock the power of convenient communication with near real-time voice translations, right through your Samsung Phone app NOTE SMARTER, NOT HARDER: Focus on capturing your notes and spend less time perfecting them; Note Assist³ will summarize, format, and even translate them for you; All of your notes are organized neatly so that you can find what you need BRING DETAILS OUT OF THE DARKNESS: Brighten up your night with Nightography on S24 Ultra; Want a closer look? Zoom in from a distance, even in low light MORE WOW, LESS WORK: Turn every photo into a post-worthy masterpiece; Move or remove objects; Fill in empty space; Simply snap a pic and take it from great to jaw-dropping with Generative Edit⁴ CAPTURE. SHARE. IMPRESS: Create crystal-clear content worth sharing; From bustling cityscape to a serene landscape, capture a masterpiece of detail with 200MP camera and let S24 Ultra adjust each hue and shade to reflect the world as you see it OUR MOST POWERFUL GALAXY SMARTPHONE YET: Jump seamlessly between apps without the wait and see content in high quality with our fastest processor yet, Snapdragon 8 Gen 3 for Galaxy⁵",
      category: "Phone",
      brand: "samsung",
      specification: [
        {Oprating_System: "Android 14, One UI 6.1"},
        {Ram_Memory: "12 GB"},
         { Memory_storage :"512 GB"}
      ],
    image:
      "https://m.media-amazon.com/images/I/71ZoDT7a2wL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    rating: 3,
    quantity: 1,
  },
  {
    id: "18568930026",
    title: "Fitness Tracker Watch with Heart Rate Monitor, Activity Tracker with Pedometer, Sleep Monitor, Calories & Step Counter, 5ATM Waterproof Smart Watch for Women Men Health Fitness Watch for Sports",
    isNew: true,
    inStock: true,
    oldPrice: "30",
    price: 19,
    description:" Heart Rate and Sleep Monitoring: The Fitness Tracker monitors your heart rate automatically all day, and you can select manual mode through the App. The fitness Watch also monitors your sleep at night, providing a detailed analysis of your sleep quality (deep sleep, light sleep, awake time). It is a health advisor for women men in daily life. Multi Sport Modes with Activity Tracking: The fitness tracker features 9 sport modes like running, walking and more. Additionally, the activity tracker records daily steps, calories burned, walking distance and active time throughout the day. You can also set a daily steps goals through the App to track your progress.Smart Notification Reminder: You can get SMS messages, and SNS notifications directly on your wrist including Facebook, Twitter, Gmail ect. You won't miss any important calls and message and stay updated. Please note: the smart watch can not make calls or text. Long Battery Life and IP68 Waterproof: This smart watch only requires 2 hours of charging and can be used for 5-7 days continuously. 5ATM waterproof rating can withstand daily sweat, washing hands and rainy day, allowing you to fully enjoy your workouts.",
      category: "watch",
    brand: "apple",
    image:
      "https://m.media-amazon.com/images/I/71sATQpfivL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    rating: 4,
    quantity: 1,
  },
  {
    id: "76478899923",
    title: "Apple iPhone 13, 128GB, Blue",
    isNew: true,
    inStock: true,
    oldPrice: "600",
    price: 489,
    description:"6.1 Super Retina XDR display. 5G Superfast downloads, high?quality streaming Cinematic mode in 1080p at 30 fps. Dolby Vision HDR video recording up to 4K at 60 fps. 2X Optical zoom range A15 Bionic chip. New 6-core CPU with 2 performance and 4 efficiency cores. New 4-core GPU. New 16-core Neural Engine  Up to 19 hours video playback. Face ID. Ceramic Shield front. Aerospace-grade aluminum",
     category: "Phone",
     brand: "apple",
    image:
      "https://m.media-amazon.com/images/I/51ysOQMyoGL._AC_SX679_.jpg",
    rating: 2,
    quantity: 1,
  },
  {
    id: "12546783993",
    title: "ZIHNIC Bluetooth Headphones Over-Ear, Foldable Wireless and Wired Stereo Headset Micro SD/TF, FM for Cell Phone,PC,Soft Earmuffs &Light Weight for Prolonged Wearing(Rose Gold)",
    isNew: true,
    inStock: true,
    oldPrice: "36",
    price: 21,
    description:"【ASTONISHING SOUND PRODUCTION 】: High Definition Stereo Headphones, specially developed software and noise reduction technology designed to prevent you from heating ambient noises and makes you focus on what you want to hear. Lose yourself in immersive music even in the lowest volume levels! The goal that provide Customers with outstanding sound quality is our constant pursuit【BUILT FOR YOUR COMFORTABILITY 】: The Earmuff is made by artificial leather, ensuring lasting comfort. They are foldable and stretchable, which allows you to find the perfect fit without constraint and excellent durability. Zihnic is the best choice for travel, sport and daily use by Unisex Kids, Teens and Adults.【SEAMLESS BLUETOOTH CONNECTION】: Built to provide a quick and stable Bluetooth connection . Just slide the on/off button and the headphones will be in ready to pair mode. The Wireless Headphones are compatible with all Bluetooth or 3.5mm plug cable enabled devices! You can also receive calls and have hands-free communication through the special noise reduction technology microphone Zihnic Headphones are compatible with all Phones X, 8 Plus, Samsung S9, S8, Pads, Pods, Huawei, Nexus, Amazon Alex",
     category: "Headphone",
    brand: "zihnic",
    image:
      "https://m.media-amazon.com/images/I/51eAhFCg5mL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    rating: 3,
    quantity: 1,
  },
  {
    id: "1367489930903",
    title: "AILIHEN C8 Headphones Wired, On-Ear Headphones with Microphone and Volume Control Foldable Corded Stereo 3.5mm Headset for Smartphones Chromebook Laptop Computer PC Tablets Travel(Black/Blue)",
    isNew: true,
    inStock: true,
    oldPrice: "46",
    price: 19,
    description:"Collapsible Feature: Take your wired headphones wherever you go. Just fold them up, twist up the cord, and be on your merry way Hands-free Talking and Volume Control: The built-in mic,remote and volume control lets you pick up calls and skip between tracks without missing a beat. Adjustable Hinge: The adjustable headband gives your headphones some impressive flexibility so they can adapt to the shape of your head for a perfect fit. Noise Isolation: full-sized, on-ear construction isolates from outside noise so you can hear the deep bass, and crisp mids and highs of your upcoming track. Widely Compatible: with a flexible and durable 47 inches braided cord and sturdy 3. 5 mm stereo Plug. Will not kink, twist or break under normal use. Use with all your favorite devices like cellphones, laptop, computer, Chromebook, MP3, MP4 and other Audio devices",
     category: "Headphone",
    brand: "ailihen",
    image:
      "https://m.media-amazon.com/images/I/81AMLwVWSfL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    rating: 4,
    quantity: 1,
  },
  {
    id: "145658930478",
    title: "BestOffice High-Back Gaming Chair PC Office Chair Computer Racing Chair PU Desk Task Chair Ergonomic Executive Swivel Rolling Chair with Lumbar Support for Back Pain Women, Men,White",
    isNew: true,
    inStock: true,
    oldPrice: "100",
    price: 89,
    description:"Pu Leather COMFORT FROM EVERY ANGLE - Our high-back gaming chair is thickly cushioned for maximum comfort, whether you’re spending long hours at the office, in front of the computer, or gaming. Covered with breathable premium PU leather, the chair is equipped with freely adjustable lumbar support and a headrest pillow to protect your spine and neck, while the adjustable reclining feature allows users to lock in any reclining position, from 90-135°. MAXIMUM MOBILITY - Our chair are designed with long-lasting ergonomic construction, equipped with a BIFMA-certified heavy-duty metal base, providing stability and mobility with a 360° range of motion on smooth-rolling nylon casters so you can glide easily between work stations. EASY ASSEMBLY – Our chair comes ready to assemble, with all the hardware and necessary tools. With step-by-step instructions, you’ll be set up and ready to game, take on the office in about 10-15 minutes! CUSTOMER GUARANTEE – We want all of our customers to feel 100% satisfied, and ready to unwind from the comfort of our High-Back Office Chair. If you’re not satisfied, or have any questions, please contact BestOffice customer service. BUILT TO LAST - The high-back chair is built to endure, with a heavy-duty metal base, offering great stability and mobility for a capacity of up to 250 lbs.",
      category: "chair",
    brand: "ergonomic chair",
    image:
      "https://m.media-amazon.com/images/I/61t4mpabO+L._AC_SY300_SX300_.jpg",
    rating: 2,
    quantity: 1,
  },
  {
    id: "156784990956",
    title: " GTRACING Gaming Chair with Footrest Speakers Video Game Chair Bluetooth Music Heavy Duty Ergonomic Computer Office Desk Chair Red",
    isNew: true,
    inStock: true,
    oldPrice: "200",
    price: 150,
    description:"Designed with 2 Bluetooth speakers.Surrounded sound system brings the best in your entertainment Connect it to your smartphone, tablet or other Bluetooth enabled devices,and enjoy music,mobile gameErgonomic Design: Strong metal frame designed to help promote a comfortable seated position Multi Function: Bluetooth speakers for 16 hour music play,Armrest adjustable,Seat height adjustable Seat height adjustable;90 to 160 degree reclining;360 degree swivel;Removable headrest High Quality: Smooth Pu leather upholstery.Thick padded seat cushion made of high density foam  Game and Office: Gtracing gaming chair is an ideal seat of choice for working, studying and gaming",
       category: "chair",
    brand: "gtracing",
    image:
      "https://m.media-amazon.com/images/I/71y9SgG-XaS.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    rating: 4,
    quantity: 1,
  },
  {
    id: "1656748909256",
    title: "Redragon S101 Gaming Keyboard, M601 Mouse, RGB Backlit Gaming Keyboard, Programmable Backlit Gaming Mouse, Value Combo Set",
    isNew: true,
    inStock: true,
    oldPrice: "60",
    price: 35,
    description:"PC GAMING KEYBOARD AND GAMING MOUSE COMBO: Includes Redragon RGB Backlit Computer Gaming Keyboard and RGB Backlit Gaming Mouse. ALL-IN-ONE PC GAMER VALUE KIT, Fantastic for Gamers (New Improved Version) RGB BACKLIT GAMING KEYBOARD; 7 different RGB Lighting modes & effects, 4 backlight brightness levels, adjustable breathing speed. The keycaps offering clear uniform backlighting WIN key can be disabled for gaming. The PC Gaming Keyboard has been ergonomically designed to be a superb typing tool for office work as well. The gaming Keyboard is built to withstand the average liquid spill. The integrated wrist rest gives you the comfort you need for marathon gaming sessions MULTI MEDIA & ANTI GHOSTING; The Gaming Keyboard has 25 conflict free (n-Key Rollover) 10 Dedicated Multimedia keys plus 12 additional FN+ Multimedia keys (Total 114 keys). Keys are quiet, designed for longevity, durability delivering precise tactile feedback. Comes with Full numeric keypad and a gold-plated corrosion free USB connector for a reliable connection and ultimate Gaming performance",
     category: "Keyboard",
    brand: "redragon",
    image:
      "https://m.media-amazon.com/images/I/71QDJHG1PqL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    rating: 4,
    quantity: 1,
  },
 ]

 export const bestselling = [
  {
  id: "5676849392",
  title: "TECKNET Wireless Mouse, 2.4G USB Computer Mouse with 6-Level Adjustable 4800 DPI, 30 Months Battery, Ergonomic Grips, 6 Buttons Portable for PC, Chromebook, Mac - Grey",
  isNew: true,
  inStock: true,
  oldPrice: "15",
  price: 9,
  description:"TECKNET wireless mouse has a 6-Level adjustable DPI (800/1200/1600/2400/3200/4800), which provides more sensitivity than standard optical mice for smooth and precise tracking on a wide range of surfaces.Designed with the upgraded independent power switches and sleep modes to minimize battery consumption, the wireless mouse can enjoy up to 30 months of use time with only 2 AA batteries (not included). 2X longer battery life than others.The wireless mouse has a 50ft/15m wireless use range, which reduces interference and delay for you. No need to install any drivers, plug the TECKNET wireless mouse into the device and you are ready to go!",
  category: "Mouse",
  brand: "tecknet",
  image:
    "https://m.media-amazon.com/images/I/61agI90cKJL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
  rating: 4,
  quantity: 1,
},
{
  id: "25474378893",
  title: "Logitech M185 Wireless Mouse, 2.4GHz with USB Mini Receiver, 12-Month Battery Life, 1000 DPI Optical Tracking, Ambidextrous PC/Mac/Laptop - Swift Gray",
  isNew: true,
  inStock: true,
  oldPrice: "18",
  price: 15,
  description:" With a comfortable and contoured shape, this Logitech ambidextrous wireless mouse feels great in either right or left hand and is far superior to a touchpad This USB wireless mouse features a line-by-line scroll wheel; up to 1 year of battery life (2) thanks to a smart sleep mode function, and comes with the included AA battery Your Logitech mouse works with your Windows PC, Mac, or laptop, so no matter what type of computer you own today or buy tomorrow your mouse will be compatible Just plug in the tiny nano USB receiver and start working in seconds with a strong, reliable connection to your wireless computer mouse up to 33 feet / 10 m (5) Get more done by adding M185 to your laptop; according to a recent study, laptop users who chose this mouse over a touchpad were 50% more productive (3) and worked 30% faster (4)",
    category: "Mouse",
    brand: "logitech",
  image:
    "https://m.media-amazon.com/images/I/61N+CzcA8vL._AC_SY300_SX300_.jpg",
  rating: 3,
  quantity: 1,
},
{
  id: "3638901297783",
  title: "Manhattan Wired Computer Keyboard – Basic Black Keyboard - with 4.5ft USB-A Cable, 104-keys, Foldable Stands - Compatible for Windows, PC, Laptop - 3 Yr Mfg Warranty – 179324",
  isNew: true,
  inStock: true,
  oldPrice: "20",
  price: 18.99,
  description:"Full-sized Keyboard: Offers 104 keys, including navigational controls, full functions and a 10-key keypad Easily connects you to your PC or laptop right away so you can get working or playing Keyboard's 4.5ft. wired connection gives you plenty of room to setup your keyboard where you want it Includes key status indicators for Num Lock, Caps Lock, Scroll Lock functions",
  category: "Keyboard",
  brand: "manhattan",
  image:
    "https://m.media-amazon.com/images/I/61s6ZL3Vg3L.__AC_SX300_SY300_QL70_FMwebp_.jpg",
  rating: 3,
  quantity: 1,
},
{
  id: "474889930023",
  title: "22 Inch Monitor with HDMI VGA Port, 1080P 75Hz Full HD VA LED Ultra Thin Bezel Display, Flicker-Free, Blue Light Filter, Built-in Speakers, Tilt Adjustment",
  isNew: true,
  inStock: true,
  oldPrice: "96",
  price: 65.96,
  description:" 21.5-inch monitor, resolution: 1920*1080P, 75HZ, color gamut 99% sRGB (NTSC 72%), response time 6ms, dynamic contrast ratio 20 million.This moniter uses VA LED Display, horizontal and vertical viewing angle 178 degrees, and unique anti-blue light filtering function. Protect your eyes while providing you with better picture quality. We care about the health of the user's neck. Norcent computer moniters has an adjustable tilt angle from 5° to -15°. Norcent monitor has HDMI, VGA, 3.5mm audio output ports, easy to link various devices. Let this monitor be your partner when you are gaming/assistant when you are working/companion when you are relaxing. The Norcent team is committed to providing customers with quality products and services. If you have any problems after purchasing our products, you can contact us at any time and we will help you solve your problems at the first time.",
  category: "Monitor",
  brand: "monitor",
  image:
    "https://m.media-amazon.com/images/I/61yezqnxooL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
  rating: 3,
  quantity: 1,
},
{
  id:"564834903092" ,
  title: "HP 14 Laptop Ultral Light for Students and Business, Quad-Core Intel Celeron Processor, 8GB RAM, 256GB Storage (128GB eMMC + 128GB Ghost Manta SD Card), HDMI, WiFi, USB-A&C, Win 11 ",
  isNew: true,
  inStock: true,
  oldPrice: "500",
  price: 357,
  description:"14.0-inch diagonal, HD (1366 x 768), micro-edge, BrightView. With virtually no bezel encircling the display, an ultra-wide viewing experience provides for seamless multi-monitor set-ups Intel Celeron N4120, 4 Cores & 4 Threads, 1.10 GHz Base Frequency, Up to 2.60 GHz Burst Frequency, 4 MB Cahce, Intel UHD Graphics 600, Handle multitasking reliably with the perfect combination of performance, power consumption, and value. Upgraded to 8GB high-bandwidth DDR4 Memory (2400 MHz), Adequate high-bandwidth RAM to smoothly run multiple applications and browser tabs all at once. 128GB high-speed eMMC Storage for your office and webinar needs. With 128GB Ghost Manta SD Card.",
  category: "Laptop",
  brand: "hp",
  image:
    "https://m.media-amazon.com/images/I/61cW3oKmQBL.__AC_SY300_SX300_QL70_FMwebp_.jpg",
  rating: 5,
  quantity: 1,
},
{
  id: "67684993092",
  title: "HP 14 Laptop Ultral Light for Students and Business, Quad-Core Intel Celeron Processor,",
  isNew: true,
  inStock: false,
  oldPrice: "350",
  price: 259,
  description:"14.0-inch diagonal, HD (1366 x 768), micro-edge, BrightView. With virtually no bezel encircling the display, an ultra-wide viewing experience provides for seamless multi-monitor set-ups Intel Celeron N4120, 4 Cores & 4 Threads, 1.10 GHz Base Frequency, Up to 2.60 GHz Burst Frequency, 4 MB Cahce, Intel UHD Graphics 600, Handle multitasking reliably with the perfect combination of performance, power consumption, and value. Upgraded to 16GB high-bandwidth DDR4 Memory (2400 MHz), Adequate high-bandwidth RAM to smoothly run multiple applications and browser tabs all at once. 128GB high-speed eMMC Storage for your office and webinar needs. With 64GB Ghost Manta SD Card.",
 category: "Laptop",
 brand: "hp",
  image:
    "https://m.media-amazon.com/images/I/61IKSn0q9bL.__AC_SY300_SX300_QL70_FMwebp_.jpg",
  rating: 4,
  quantity: 1,
},
{
  id: "76478899923",
  title: "Apple iPhone 13, 128GB, Blue ",
  isNew: true,
  inStock: true,
  oldPrice: "600",
  price: 489,
  description:"6.1 Super Retina XDR display. 5G Superfast downloads, high?quality streaming Cinematic mode in 1080p at 30 fps. Dolby Vision HDR video recording up to 4K at 60 fps. 2X Optical zoom range A15 Bionic chip. New 6-core CPU with 2 performance and 4 efficiency cores. New 4-core GPU. New 16-core Neural Engine  Up to 19 hours video playback. Face ID. Ceramic Shield front. Aerospace-grade aluminum",
   category: "Phone",
   brand: "apple",
  image:
    "https://m.media-amazon.com/images/I/51ysOQMyoGL._AC_SX679_.jpg",
  rating: 2,
  quantity: 1,
},
{
  id: "853789209834",
  title: "Samsung Galaxy S21 FE 5G, Factory Unlocked, 128GB, 120Hz Display Screen, Pro Grade Camera, US Version, White - (Renewed)",
  isNew: true,
  inStock:true,
  oldPrice: "300",
  price: 205,
  description:"6.4 FHD+ Dynamic AMOLED 2X, Infinity-O Display (2400x1080), 401ppi, HDR10+ certified, 120Hz refresh rate 128GB ROM, 6GB RAM, Qualcomm SM8350 Snapdragon 888 5G (5 nm), Octa-core, 4500mAh Battery Rear Camera: 12MP Ultra-Wide + 12MP Wide-angle + 8MP Telephoto, Front Camera: 32MP, Under Display Fingerprint 2G: GSM 850/900/1800/1900, CDMA 800/1900 / TD-SCDMA, 3G: HSDPA 850/900/1700(AWS)/1900/2100, CDMA2000 1xEV-DO, 4G: LTE 1/2/3/4/5/7/12/13/29/25/26/28/38/39/40/41/46/48/66/71, 5G: 41/66/71/260/261 SA/NSA/Sub6 (ensure to check compatibility with your carrier before purchase) US Model. Fully Unlocked Version. Compatible with Most GSM and CDMA Carriers like AT&T, T-Mobile, AT&T, MetroPCS, etc. Will Also work with CDMA Carriers Such as Verizon, Sprint.",
    category: "Phone",
    brand: "samsung",
  image:
    "https://m.media-amazon.com/images/I/61PPEjwAkYL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
  rating: 3,
  quantity: 1,
},
   ]

 


  




